name: Update js file
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: Update JS
      run: |
        cd fyfuzhi
        rm -f torn-trans-zhcn.user.js
        wget -O torn-trans-zhcn.user.js https://gitlab.com/JJins/wuhu-torn-helper/-/raw/dev/torn-trans-zhcn.user.js?inline=false
    - name: Commit & Push
      uses: EndBug/add-and-commit@v7
      with:
        branch: master
