name: Update file from gitee
on:
  # push:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: Update JS and version image
      run: |
        cd fyfuzhi
        rm -f torn-trans-zhcn.user.js
        wget https://gitee.com/wanyi007/torncity-zhcn-translate/raw/dev/torn-trans-zhcn.user.js
        python -m pip install pygame
        python -m pip install pillow
        cd ../t2i
        rm -f version.png
        ls -a
        echo "generating png"
        python t2i.py
        ls -a
    - name: Commit & Push
      uses: EndBug/add-and-commit@v7
      with:
        branch: master
