name: Update js file
on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: Update JS
      run: |
        cd fyfuzhi
        rm -f wuhu-torn-helper.js
        rm -f release.min.user.js
        #wget https://gitlab.com/JJins/wuhu-torn-helper/-/raw/dev/wuhu-torn-helper.js
        wget https://gitlab.com/JJins/wuhu-torn-helper/-/raw/dev/release.min.user.js
    - name: Commit & Push
      uses: EndBug/add-and-commit@v7
      with:
        branch: master
